Update no-food-is-fully-vegan.md
talkvegantome/talkvegan-hugo pull request #8
Opened 2019-10-03 09:58 UTC by DrTeo

Unpacked argument into 3 forms
Resonses to each argument
Doctrine of double effect
Distinction of acting with foreknowledge
Defining 'possible and practicable'.

2019-10-03 09:59 UTC, DrTeo commented
Got quite long...

In some ways it feels a bit rushed as I cut it back from growing even further.

Needs a fresh pair of eyes (mine are asleep!)

2019-10-03 12:13 UTC, Sam-Martin requested changes

2019-10-03 12:13 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> (Argument #2) "It is wrong to inflict unnecessary death on nonhuman animals and it is especially wrong , pro tanto, to do so intentionally. Where one must choose between bringing about death as a s
extra space `especially wrong ,`

2019-10-03 12:13 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +While it is true that some animals do die in the production and harvesting of crops vegans do not ‘accept these deaths’ without question.  Where a crop farmer fails to *exercise due diligence to mini
Let's keep the viva link to Vegan Farming here: 
```
[vegan farms(https://www.viva.org.uk/what-we-do/vegan-farming)
```

2019-10-03 12:13 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +While cattle farmer's *intend* to kill the cattle they raise, the crop farmer's intention is primarily to grow crops. Any deaths that may occur during crop harvest are a side-effect of a morally neut
I would prefix this sentence with something like `In other words, When cattle farmers...` as I think most people will skip over the doctrine of double effect as "intimidating philosophy words" and look to the next unquoted sentence to repeat it in laymans terms. (I think we should keep the definition to be clear as it's super clear if you take the time to read it, we just need to make 100% sure there is a simplified version that people are drawn to read).

Also `cattle farmers` rather than `cattle farmer's`

2019-10-03 12:13 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +* A cattle farmer has foreknowledge that the cattle will be slaughtered and intends for them to be slaughtered.
Can we substitute the word `has foreknowledge` with `knows without a doubt` or just `knows`?

2019-10-03 12:13 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> Rather, it is a reference to the threshold a ‘rational person’ would set; ‘all other things being equal’.
As much as I agree philosophically, I think this teeters too close to the edge of transgressing [mission statement #6](https://github.com/talkvegantome/talkvegan-hugo)

> 6 Not to engage in the gatekeeping of veganism (no-one can take away your V card)

Or at the very least provides a stepping stone for other people to do so. 

Can we do without it?

2019-10-03 12:13 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> Argument #3 misrepresents the nature of veganism. As with any moral standpoint perfection is not expected. However, there is the expectation of striving towards excellence…
Was this a note for yourself or is this intended to be left in?

2019-10-03 19:19 UTC, DrTeo commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +While cattle farmer's *intend* to kill the cattle they raise, the crop farmer's intention is primarily to grow crops. Any deaths that may occur during crop harvest are a side-effect of a morally neut
In other words a cattle farmer *intends* to kill the cattle, the crop farmer's intention is primarily to grow crops. Any deaths that may occur during crop harvest are a side-effect of a morally neutral act.

2019-10-03 19:22 UTC, DrTeo commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +* A cattle farmer has foreknowledge that the cattle will be slaughtered and intends for them to be slaughtered.
Left first foreknowledge.

Changed seconds to: 

A cattle farmer knows that the cattle will be slaughtered and intends for them to be slaughtered.

and

A crop farmer knows that some animals (e.g rabbits, birds, rodents) may be killed...

2019-10-03 19:36 UTC, DrTeo commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> Argument #3 misrepresents the nature of veganism. As with any moral standpoint perfection is not expected. However, there is the expectation of striving towards excellence…
Yes and no.   I was asleep at this point.  An ending to the section / Argument #3

How about:

Argument #3 misrepresents the nature of veganism. As with any moral standpoint perfection is not expected. Veganism, and the ideal of a world without exploitation and cruelty, is both logical and possible.

2019-10-04 07:50 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +While cattle farmer's *intend* to kill the cattle they raise, the crop farmer's intention is primarily to grow crops. Any deaths that may occur during crop harvest are a side-effect of a morally neut
perfect 👍

2019-10-04 07:51 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +* A cattle farmer has foreknowledge that the cattle will be slaughtered and intends for them to be slaughtered.
Works for me!

2019-10-04 07:53 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> Argument #3 misrepresents the nature of veganism. As with any moral standpoint perfection is not expected. However, there is the expectation of striving towards excellence…
Rather than adding a caveat at the end can we tweak argument three to represent the messiness of reality? As that misrepresentation is a bit of an issue! (see other comment)

2019-10-06 20:18 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +While it is true that some animals do die in the production and harvesting of crops vegans do not ‘accept these deaths’ without question.  Where a crop farmer fails to *exercise due diligence to mini
`[vegan farms] (https://www.viva.org.uk/what-we-do/vegan-farming)` doesn't work as a link, the space needs removing!

2019-10-06 20:23 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> You are controlling a tram. As long as you hold a lever the tram will continue on its current track.  However, you know there are numerous people on the track ahead who will be killed if the tram c
Can we remove some of the qualifiers on this? Specifically:
- Numerous
- Very probably

So we would get 

>  You are controlling a tram. As long as you hold a lever the tram will continue on its current track.  However, you *know* there are people on the track ahead who will be killed if the tram continues.  
> If you release the lever the tram will change tracks. You *suspect* there are people on the other track as well.

It conveys the same uncertainty but makes it easier to discern the difference.

2019-10-06 20:24 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +1. Continuing to hold the lever is to kill with both foreknowledge and intent.
I think we can just say *knowledge* here.

2019-10-06 20:25 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +2. Releasing the lever is to have the foreknowledge that some people might be killed.
I think we can just say *know* here and emphasise *might*.

2019-10-06 20:26 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +Knowingly risking some deaths is morally preferable to knowingly killing with intent.
Can we say
> Knowingly risking some deaths is morally preferable to killing with certainty and intent.
I think it's easier to read.

2019-10-06 20:27 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +Humans hold a lever which results in the intentional deaths of millions of animals. It's time to let go of the lever; the foreknowledge that some animals will probably die as a result of crop farming
I love this so much, if we ever sell t-shirts we need one that says "let go of the lever".

2019-10-06 20:27 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> Vegans do not accept the deaths of some animals to produce our foods of preference. While vegans have foreknowledge that this may occur it is not the intent and, wherever possible, steps are taken
Let's just say 'While vegans know that this may occur". The foreknowledge isn't doing any useful work for the layman reading this.

2019-10-06 20:28 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +>  There is considerable moral difference between slaughtering animals with intent and deaths that occur as an unintentional side effect of crop farming, even where we have foreknowledge the deaths m
We can get away with `know` again I think.

2019-10-06 20:29 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +The claim that ‘veganism is logically impossible' misrepresents the nature of veganism. As with any moral standpoint perfection is not expected. Rather, vegans strive toward the ideal of a world with
Perfect, love this too.

2019-10-06 20:29 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +Nor is it an excuse to not learn those pesky [E-numbers] ({{< ref "../shopping/e-numbers" >}}). The mistreatment of animals does not compare to committing these to memory, or carrying around the Talk
the space needs removing in this link too. It should be:
```
[E-numbers]({{< ref "../shopping/e-numbers" >}})
```

2019-10-06 20:30 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
>  > It's impossible to have completely vegan food. Fertilizers are derived from animal waste and bones, pesticides are used on crops to kill insects, bees are kept in hives to pollinate almonds, worms
Do you mind adding 'portable' to hives while you're here @DrTeo ?

2019-10-06 20:31 UTC, Sam-Martin commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> (Argument #2) "It is wrong to inflict unnecessary death on nonhuman animals and it is especially wrong, pro tanto, to do so intentionally. Where one must choose between bringing about death as a si
Can we add `[(all other things being equal)]` after pro tanto like Val suggests?

2019-10-06 20:58 UTC, DrTeo commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +While it is true that some animals do die in the production and harvesting of crops vegans do not ‘accept these deaths’ without question.  Where a crop farmer fails to *exercise due diligence to mini
Weird. Don't have a space (in my local copy) and it works fine (locally).  re-editing it anyway in the hope it fixes....

2019-10-06 21:08 UTC, DrTeo commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +>  There is considerable moral difference between slaughtering animals with intent and deaths that occur as an unintentional side effect of crop farming, even where we have foreknowledge the deaths m
Think the point is logically stronger using foreknowledge on this occasion.  Not stuck on it though. Will change if you think its a biggie.

2019-10-06 21:28 UTC, DrTeo commented on content/english/anti-vegan/no-food-is-fully-vegan.md
> +> (Argument #2) "It is wrong to inflict unnecessary death on nonhuman animals and it is especially wrong, pro tanto, to do so intentionally. Where one must choose between bringing about death as a si
No.   Well not really... it's doesn't really capture the meaning.

That said I couldn't come up with anything short that did. I've currently ...'d it out (Didn't want to but it either that or a paragraph of explanation.

2019-10-06 22:23 UTC, Sam-Martin approved these changes

2019-10-06 22:23 UTC, merged